# Generated by Django 5.2.15 on 2026-06-19 01:29

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterialBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=50, unique=True, verbose_name='批次编号')),
                ('material_source', models.CharField(max_length=100, verbose_name='原料来源')),
                ('material_weight', models.FloatField(verbose_name='原料重量(kg)')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='开始日期')),
                ('operator', models.CharField(max_length=50, verbose_name='操作人员')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '原料批次',
                'verbose_name_plural': '原料批次',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_type', models.CharField(choices=[('leaching', '浸取'), ('filtration', '过滤'), ('evaporation', '蒸发'), ('crystallization', '结晶')], max_length=20, verbose_name='工序阶段')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('status', models.CharField(choices=[('in_progress', '进行中'), ('completed', '已完成'), ('paused', '已暂停')], default='in_progress', max_length=20, verbose_name='状态')),
                ('operator', models.CharField(blank=True, max_length=50, verbose_name='操作人员')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.rawmaterialbatch', verbose_name='批次')),
            ],
            options={
                'verbose_name': '工序阶段',
                'verbose_name_plural': '工序阶段',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='InspectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_type', models.CharField(choices=[('leaching', '浸取'), ('filtration', '过滤'), ('evaporation', '蒸发'), ('crystallization', '结晶')], max_length=20, verbose_name='工序阶段')),
                ('inspection_date', models.DateField(default=datetime.date.today, verbose_name='检测日期')),
                ('temperature', models.FloatField(verbose_name='温度(°C)')),
                ('concentration', models.FloatField(verbose_name='浓度(%)')),
                ('ph_value', models.FloatField(blank=True, null=True, verbose_name='pH值')),
                ('operator', models.CharField(max_length=50, verbose_name='检测人员')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.rawmaterialbatch', verbose_name='批次')),
            ],
            options={
                'verbose_name': '检测记录',
                'verbose_name_plural': '检测记录',
                'ordering': ['-inspection_date'],
            },
        ),
        migrations.CreateModel(
            name='CrystallizationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crystal_weight', models.FloatField(verbose_name='结晶重量(kg)')),
                ('crystal_purity', models.FloatField(default=95.0, verbose_name='结晶纯度(%)')),
                ('crystallization_date', models.DateField(default=datetime.date.today, verbose_name='结晶日期')),
                ('operator', models.CharField(max_length=50, verbose_name='操作人员')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='production.rawmaterialbatch', verbose_name='批次')),
            ],
            options={
                'verbose_name': '结晶结果',
                'verbose_name_plural': '结晶结果',
            },
        ),
        migrations.CreateModel(
            name='AbnormalDisposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abnormal_type', models.CharField(choices=[('low_yield', '产率偏低'), ('low_purity', '纯度偏低'), ('equipment', '设备故障'), ('process', '工艺异常'), ('other', '其他')], max_length=20, verbose_name='异常类型')),
                ('stage_type', models.CharField(choices=[('leaching', '浸取'), ('filtration', '过滤'), ('evaporation', '蒸发'), ('crystallization', '结晶')], max_length=20, verbose_name='发生阶段')),
                ('discover_date', models.DateField(default=datetime.date.today, verbose_name='发现日期')),
                ('description', models.TextField(verbose_name='异常描述')),
                ('reason', models.TextField(verbose_name='异常原因')),
                ('disposal_measure', models.TextField(blank=True, verbose_name='处置措施')),
                ('disposal_status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('resolved', '已解决'), ('closed', '已关闭')], default='pending', max_length=20, verbose_name='处置状态')),
                ('handler', models.CharField(blank=True, max_length=50, verbose_name='处理人员')),
                ('resolve_date', models.DateField(blank=True, null=True, verbose_name='解决日期')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.rawmaterialbatch', verbose_name='批次')),
            ],
            options={
                'verbose_name': '异常处置',
                'verbose_name_plural': '异常处置',
                'ordering': ['-discover_date'],
            },
        ),
    ]
