# Generated by Django 5.2.15 on 2026-06-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_sourcecoststats_batchcostsummary_laborcost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='othercost',
            name='quantity',
            field=models.FloatField(default=1, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='othercost',
            name='unit_price',
            field=models.FloatField(default=0, verbose_name='单价(元)'),
        ),
    ]
