# Generated by Django 5.2.15 on 2026-06-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_alter_othercost_quantity_alter_othercost_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchcostsummary',
            name='loss_cost',
            field=models.FloatField(default=0, verbose_name='损耗费用(元)'),
        ),
        migrations.AddField(
            model_name='sourcecoststats',
            name='abnormal_count',
            field=models.IntegerField(default=0, verbose_name='异常总次数'),
        ),
        migrations.AddField(
            model_name='sourcecoststats',
            name='avg_crystallization_purity',
            field=models.FloatField(blank=True, null=True, verbose_name='平均纯度(%)'),
        ),
        migrations.AddField(
            model_name='sourcecoststats',
            name='avg_crystallization_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='平均结晶率(%)'),
        ),
        migrations.AddField(
            model_name='sourcecoststats',
            name='avg_loss_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='平均损耗费用(元)'),
        ),
    ]
