# Generated by Django 5.2.15 on 2026-06-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_equipment_equipmentinspection_equipmentstatusrecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentstatusrecord',
            name='stage_type',
            field=models.CharField(blank=True, choices=[('leaching', '浸取'), ('filtration', '过滤'), ('evaporation', '蒸发'), ('crystallization', '结晶')], max_length=20, null=True, verbose_name='工序阶段'),
        ),
    ]
